spring.application.name=PkmsBackend
pkms.vault.inbox-path=C:/Users/elipk/Desktop/Elias_2026/Elias_Personal_Notes/Elias Gedanken/0_Posteingang
pkms.vault.attachment-directory=_attachments
pkms.sync.index-path=./data/synced-captures-prod.properties
